Twitter {
  VERSION: '1.7.1',
  options:
   { consumer_key: 'olxRgDRbWfS6rK9g2sLu8apEo',
     consumer_secret: 'yuq2olLunQsqn93RQOZelo0nKq34vNGuKaQBUNH6uRFHYTQped',
     access_token_key: '876816001882574848-KEXHHWZFV0BqtPASq0pPuHtc9g3XLCo',
     access_token_secret: 'UxRoLpQnWPIEzXoen2FSYGUfdsKhAKN7gw7gCEuK95vKd',
     bearer_token: null,
     rest_base: 'https://api.twitter.com/1.1',
     stream_base: 'https://stream.twitter.com/1.1',
     user_stream_base: 'https://userstream.twitter.com/1.1',
     site_stream_base: 'https://sitestream.twitter.com/1.1',
     media_base: 'https://upload.twitter.com/1.1',
     request_options: { headers: [Object], oauth: [Object] } },
  request:
   { [Function]
     get: [Function],
     head: [Function],
     post: [Function],
     put: [Function],
     patch: [Function],
     del: [Function],
     delete: [Function],
     cookie: [Function],
     jar: [Function],
     defaults: [Function] },
  allow_promise: true }
[ { created_at: 'Mon Jun 19 16:36:35 +0000 2017',
    id: 876841148945489900,
    id_str: '876841148945489920',
    text: 'Talking to myself and it\'s alright.',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 876816001882574800,
       id_str: '876816001882574848',
       name: 'Whitney Wong',
       screen_name: 'Whitney56113545',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Mon Jun 19 14:56:40 +0000 2017',
       favourites_count: 0,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 3,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Mon Jun 19 16:36:03 +0000 2017',
    id: 876841013528186900,
    id_str: '876841013528186880',
    text: 'It\'s fun programming :)',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 876816001882574800,
       id_str: '876816001882574848',
       name: 'Whitney Wong',
       screen_name: 'Whitney56113545',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Mon Jun 19 14:56:40 +0000 2017',
       favourites_count: 0,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 3,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Mon Jun 19 14:59:36 +0000 2017',
    id: 876816740382109700,
    id_str: '876816740382109696',
    text: 'First tweet!',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 876816001882574800,
       id_str: '876816001882574848',
       name: 'Whitney Wong',
       screen_name: 'Whitney56113545',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Mon Jun 19 14:56:40 +0000 2017',
       favourites_count: 0,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 3,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' } ]